/****************************************************************************
*
*                          PUBLIC DOMAIN NOTICE                         
*         Lister Hill National Center for Biomedical Communications
*                      National Library of Medicine
*                      National Institues of Health
*           United States Department of Health and Human Services
*                                                                         
*  This software is a United States Government Work under the terms of the
*  United States Copyright Act. It was written as part of the authors'
*  official duties as United States Government employees and contractors
*  and thus cannot be copyrighted. This software is freely available
*  to the public for use. The National Library of Medicine and the
*  United States Government have not placed any restriction on its
*  use or reproduction.
*                                                                        
*  Although all reasonable efforts have been taken to ensure the accuracy 
*  and reliability of the software and data, the National Library of Medicine
*  and the United States Government do not and cannot warrant the performance
*  or results that may be obtained by using this software or data.
*  The National Library of Medicine and the U.S. Government disclaim all
*  warranties, expressed or implied, including warranties of performance,
*  merchantability or fitness for any particular purpose.
*                                                                         
*  For full details, please see the MetaMap Terms & Conditions, available at
*  https://metamap.nlm.nih.gov/MMTnCs.shtml.
*
***************************************************************************/

% File:	    frequent_firsst_word_pair.pl
% Module:   MetaMap
% Author:   FML
% Purpose:  MetaMap frequent first word pairs generated by 0doit4 in the $MWI directory

:- module(frequent_first_word_pair, [
	frequent_first_word_pair/2
    ]).

frequent_first_word_pair('2',                   'acid').
frequent_first_word_pair('3',                   'acid').
frequent_first_word_pair('4',                   'acid').
frequent_first_word_pair('accidental',          'poisoning').
frequent_first_word_pair('activation',          'activity').
frequent_first_word_pair('anterior',            'nerve').
frequent_first_word_pair('anti',                'antibody').
frequent_first_word_pair('arabidopsis',         'protein').
frequent_first_word_pair('articular',           'vertebra').
frequent_first_word_pair('bacillus',            '1').
frequent_first_word_pair('bacillus',            'protein').
frequent_first_word_pair('bacteria',            'protein').
frequent_first_word_pair('bony',                'bone').
frequent_first_word_pair('bony',                'vertebra').
frequent_first_word_pair('c',                   'protein').
frequent_first_word_pair('cdisc',               'terminology').
frequent_first_word_pair('cecidomyiidae',       '10').
frequent_first_word_pair('compact',             'bone').
frequent_first_word_pair('compact',             'vertebra').
frequent_first_word_pair('ctcae',               'injury').
frequent_first_word_pair('down',                'activity').
frequent_first_word_pair('downregulation',      'activity').
frequent_first_word_pair('drosophila',          'protein').
frequent_first_word_pair('e',                   'protein').
frequent_first_word_pair('entire',              'artery').
frequent_first_word_pair('entire',              'muscle').
frequent_first_word_pair('entire',              'vein').
frequent_first_word_pair('grade',               'injury').
frequent_first_word_pair('hemoglobin',          'phenotype').
frequent_first_word_pair('hla',                 'antigen').
frequent_first_word_pair('human',               '1').
frequent_first_word_pair('human',               '2').
frequent_first_word_pair('human',               'antigen').
frequent_first_word_pair('human',               'microrna').
frequent_first_word_pair('human',               'protein').
frequent_first_word_pair('inhibition',          'activity').
frequent_first_word_pair('intentional',         'poisoning').
frequent_first_word_pair('lateral',             'nerve').
frequent_first_word_pair('left',                'trunk').
frequent_first_word_pair('malignant',           'tumor').
frequent_first_word_pair('megaselia',           '10').
frequent_first_word_pair('member',              'family').
frequent_first_word_pair('mouse',               '1').
frequent_first_word_pair('mouse',               '2').
frequent_first_word_pair('mouse',               'protein').
frequent_first_word_pair('negative',            'activity').
frequent_first_word_pair('negative',            'process').
frequent_first_word_pair('periosteum',          'bone').
frequent_first_word_pair('periosteum',          'vertebra').
frequent_first_word_pair('positive',            'activity').
frequent_first_word_pair('positive',            'process').
frequent_first_word_pair('posterior',           'nerve').
frequent_first_word_pair('pseudomonas',         '1').
frequent_first_word_pair('rat',                 'protein').
frequent_first_word_pair('regulation',          'activity').
frequent_first_word_pair('regulation',          'process').
frequent_first_word_pair('right',               'artery').
frequent_first_word_pair('right',               'trunk').
frequent_first_word_pair('rnu6',                'gene').
frequent_first_word_pair('s',                   'protein').
frequent_first_word_pair('stage',               'cancer').
frequent_first_word_pair('stage',               'carcinoma').
frequent_first_word_pair('stage',               'lymphoma').
frequent_first_word_pair('stage',               'v7').
frequent_first_word_pair('stage',               'v8').
frequent_first_word_pair('structure',           'artery').
frequent_first_word_pair('surface',             'bone').
frequent_first_word_pair('surface',             'vertebra').
frequent_first_word_pair('synovial',            'joint').
frequent_first_word_pair('trabecular',          'bone').
frequent_first_word_pair('trabecular',          'vertebra').
frequent_first_word_pair('trunk',               'artery').
frequent_first_word_pair('trunk',               'nerve').
frequent_first_word_pair('trunk',               'vein').
frequent_first_word_pair('up',                  'activity').
frequent_first_word_pair('upregulation',        'activity').
frequent_first_word_pair('xenopus',             'protein').
frequent_first_word_pair('zebrafish',           'protein').
