#/*==========================================================
#
#%SOURCE FILE
#	Makefile.lib
#
#%DESCRIPTION OF FILE
#	Make file
#
#%REVISED
#	30Aug2006 FML
#	based on Makefile.lexical and Makefile.nls_signal
#	
#%SCCS:	@(#)Makefile.lib	1.1 09/15/06
#
#==========================================================*/

O_SYSTEM = $(shell uname)

ifeq '$(O_SYSTEM)' "SunOS"
  LD = ld
  LDFLAGS=-G -shared
  LIBS =
else
  ifeq '$(O_SYSTEM)' "Linux"
    LD = gcc
    LDFLAGS=-m32 -shared
    LIBS = -lpthread
  endif
endif

CFLAGS=${DEFAULT_CFLAGS}

SPLFR_BASIC_FLAGS = --verbose --keep
SPLFR_DYNAMIC_FLAGS = ${SPLFR_BASIC_FLAGS}
SPLFR_STATIC_FLAGS = ${SPLFR_BASIC_FLAGS} --static

SPLFR = splfr --conf CC=${CC} ${addprefix --cflag=, ${CFLAGS}}

# all:		nls_signal.o nls_signal.so nls_signal.a
# 
# nls_signal.a:	nls_signal.o 
# 		${AR} ${ARFLAGS} $@ $<
# 
# nls_signal.so:	nls_signal.o
# 		${LD} ${LDFLAGS} $< -o nls_signal.so ${LIBS}
# 
# nls_signal.o:	nls_signal.c 
# 		${CC} ${CFLAGS} -c $< -I${SPINCDIR}

all:		splfr_DYNAMIC splfr_STATIC

splfr_DYNAMIC:
		${SPLFR} ${SPLFR_DYNAMIC_FLAGS} nls_signal.pl nls_signal.c

	
splfr_STATIC:
		${SPLFR} ${SPLFR_STATIC_FLAGS} nls_signal.pl nls_signal.c

clean:
		-${RM} *.o *.a *.so *glue*
