
/****************************************************************************
*
*                          PUBLIC DOMAIN NOTICE                         
*         Lister Hill National Center for Biomedical Communications
*                      National Library of Medicine
*                      National Institues of Health
*           United States Department of Health and Human Services
*                                                                         
*  This software is a United States Government Work under the terms of the
*  United States Copyright Act. It was written as part of the authors'
*  official duties as United States Government employees and contractors
*  and thus cannot be copyrighted. This software is freely available
*  to the public for use. The National Library of Medicine and the
*  United States Government have not placed any restriction on its
*  use or reproduction.
*                                                                        
*  Although all reasonable efforts have been taken to ensure the accuracy 
*  and reliability of the software and data, the National Library of Medicine
*  and the United States Government do not and cannot warrant the performance
*  or results that may be obtained by using this software or data.
*  The National Library of Medicine and the U.S. Government disclaim all
*  warranties, expressed or implied, including warranties of performance,
*  merchantability or fitness for any particular purpose.
*                                                                         
*  For full details, please see the MetaMap Terms & Conditions, available at
*  http://metamap.nlm.nih.gov/MMTnCs.shtml.
*
***************************************************************************/

% File:     sentence_initial_words.pl
% Module:   sentence_initial_words
% Author:   FML
% Purpose:  Define words that are known to begin a sentence
%           immediately after a full stop with no intervening whitespace.

:- module(sentence_initial_words,[
    sentence_initial_word/1
    ]).

% These are all the words in the 2011 Medline Baseline that
% * appear immediately after a "."
% * with no intervening blank space
% * at least 4 times
% * and are no more than 6 characters long.

sentence_initial_word('AIDS').
sentence_initial_word('AIM').
sentence_initial_word('AIS').
sentence_initial_word('AIs').
sentence_initial_word('AMONG').
sentence_initial_word('AND').
sentence_initial_word('ARE').
sentence_initial_word('AUG').
sentence_initial_word('About').
sentence_initial_word('Action').
sentence_initial_word('Active').
sentence_initial_word('Acute').
sentence_initial_word('Ada').
sentence_initial_word('Ado').
sentence_initial_word('Adult').
sentence_initial_word('After').
sentence_initial_word('Again').
sentence_initial_word('Age').
sentence_initial_word('Aid').
sentence_initial_word('Aim').
sentence_initial_word('Aims').
sentence_initial_word('Air').
sentence_initial_word('Ala').
sentence_initial_word('Alaska').
sentence_initial_word('All').
sentence_initial_word('Almost').
sentence_initial_word('Alpha').
sentence_initial_word('Also').
sentence_initial_word('Am').
sentence_initial_word('Amino').
sentence_initial_word('Among').
sentence_initial_word('Anal').
sentence_initial_word('And').
sentence_initial_word('Animal').
sentence_initial_word('Anti').
sentence_initial_word('Any').
sentence_initial_word('Apart').
sentence_initial_word('App').
sentence_initial_word('Are').
sentence_initial_word('Areas').
sentence_initial_word('Array').
sentence_initial_word('Art').
sentence_initial_word('As').
sentence_initial_word('Asp').
sentence_initial_word('Asthma').
sentence_initial_word('At').
sentence_initial_word('Atlas').
sentence_initial_word('Atrial').
sentence_initial_word('Au').
sentence_initial_word('Auxin').
sentence_initial_word('BUT').
sentence_initial_word('BY').
sentence_initial_word('Baker').
sentence_initial_word('Based').
sentence_initial_word('Bax').
sentence_initial_word('Before').
sentence_initial_word('Beta').
sentence_initial_word('Biopsy').
sentence_initial_word('Black').
sentence_initial_word('Blood').
sentence_initial_word('Body').
sentence_initial_word('Bone').
sentence_initial_word('Both').
sentence_initial_word('Bragg').
sentence_initial_word('Breast').
sentence_initial_word('Brief').
sentence_initial_word('CAN').
sentence_initial_word('CARR').
sentence_initial_word('CASE').
sentence_initial_word('CAST').
sentence_initial_word('CAT').
sentence_initial_word('CATE').
sentence_initial_word('CED').
sentence_initial_word('COUP').
sentence_initial_word('Cad').
sentence_initial_word('Cal').
sentence_initial_word('Can').
sentence_initial_word('Canada').
sentence_initial_word('Cancer').
sentence_initial_word('Carbon').
sentence_initial_word('Care').
sentence_initial_word('Carr').
sentence_initial_word('Case').
sentence_initial_word('Cases').
sentence_initial_word('Cat').
sentence_initial_word('Cell').
sentence_initial_word('Cells').
sentence_initial_word('Chem').
sentence_initial_word('China').
sentence_initial_word('Clark').
sentence_initial_word('Clarke').
sentence_initial_word('Clear').
sentence_initial_word('Close').
sentence_initial_word('Code').
sentence_initial_word('Cold').
sentence_initial_word('Coll').
sentence_initial_word('Common').
sentence_initial_word('Copper').
sentence_initial_word('Cor').
sentence_initial_word('Corn').
sentence_initial_word('Cost').
sentence_initial_word('Cross').
sentence_initial_word('Crude').
sentence_initial_word('Cyclic').
sentence_initial_word('DDT').
sentence_initial_word('DESIGN').
sentence_initial_word('DNA').
sentence_initial_word('DOM').
sentence_initial_word('DOSE').
sentence_initial_word('DOT').
sentence_initial_word('Daily').
sentence_initial_word('Dane').
sentence_initial_word('Dark').
sentence_initial_word('Data').
sentence_initial_word('Date').
sentence_initial_word('Death').
sentence_initial_word('Delta').
sentence_initial_word('Dental').
sentence_initial_word('Design').
sentence_initial_word('Dimer').
sentence_initial_word('Direct').
sentence_initial_word('Dis').
sentence_initial_word('Disc').
sentence_initial_word('Does').
sentence_initial_word('Don').
sentence_initial_word('Dose').
sentence_initial_word('Doses').
sentence_initial_word('Dot').
sentence_initial_word('Double').
sentence_initial_word('Dr').
sentence_initial_word('Drug').
sentence_initial_word('Dry').
sentence_initial_word('Due').
sentence_initial_word('During').
sentence_initial_word('EAT').
sentence_initial_word('EDDA').
sentence_initial_word('EEG').
sentence_initial_word('ELISA').
sentence_initial_word('ELM').
sentence_initial_word('ERE').
sentence_initial_word('EST').
sentence_initial_word('Each').
sentence_initial_word('Early').
sentence_initial_word('Eco').
sentence_initial_word('Ed').
sentence_initial_word('Edin').
sentence_initial_word('Eight').
sentence_initial_word('Eighty').
sentence_initial_word('Eleven').
sentence_initial_word('Empty').
sentence_initial_word('End').
sentence_initial_word('Energy').
sentence_initial_word('Eng').
sentence_initial_word('Enzyme').
sentence_initial_word('Even').
sentence_initial_word('Except').
sentence_initial_word('Extra').
sentence_initial_word('Eye').
sentence_initial_word('FDA').
sentence_initial_word('FEAT').
sentence_initial_word('FLAG').
sentence_initial_word('Factor').
sentence_initial_word('Family').
sentence_initial_word('Fatty').
sentence_initial_word('Female').
sentence_initial_word('Few').
sentence_initial_word('Fibrin').
sentence_initial_word('Field').
sentence_initial_word('Fifty').
sentence_initial_word('Filter').
sentence_initial_word('First').
sentence_initial_word('Five').
sentence_initial_word('Flow').
sentence_initial_word('Follow').
sentence_initial_word('Food').
sentence_initial_word('For').
sentence_initial_word('Forty').
sentence_initial_word('Four').
sentence_initial_word('Frank').
sentence_initial_word('Free').
sentence_initial_word('Fresh').
sentence_initial_word('From').
sentence_initial_word('Full').
sentence_initial_word('Future').
sentence_initial_word('GLAND').
sentence_initial_word('GRIN').
sentence_initial_word('GROUP').
sentence_initial_word('GSA').
sentence_initial_word('GUS').
sentence_initial_word('Gene').
sentence_initial_word('George').
sentence_initial_word('Given').
sentence_initial_word('Global').
sentence_initial_word('Golden').
sentence_initial_word('Good').
sentence_initial_word('Gov').
sentence_initial_word('Grade').
sentence_initial_word('Grand').
sentence_initial_word('Graphs').
sentence_initial_word('Gray').
sentence_initial_word('Green').
sentence_initial_word('Gross').
sentence_initial_word('Group').
sentence_initial_word('Groups').
sentence_initial_word('Growth').
sentence_initial_word('Guinea').
sentence_initial_word('HIV').
sentence_initial_word('HOW').
sentence_initial_word('Hal').
sentence_initial_word('Half').
sentence_initial_word('Ham').
sentence_initial_word('He').
sentence_initial_word('Health').
sentence_initial_word('Heat').
sentence_initial_word('Heavy').
sentence_initial_word('Hence').
sentence_initial_word('Hep').
sentence_initial_word('Here').
sentence_initial_word('Herein').
sentence_initial_word('Hex').
sentence_initial_word('High').
sentence_initial_word('Higher').
sentence_initial_word('Hind').
sentence_initial_word('His').
sentence_initial_word('Hop').
sentence_initial_word('How').
sentence_initial_word('Human').
sentence_initial_word('Hunter').
sentence_initial_word('Image').
sentence_initial_word('In').
sentence_initial_word('Indeed').
sentence_initial_word('Info').
sentence_initial_word('Intact').
sentence_initial_word('Inter').
sentence_initial_word('Iron').
sentence_initial_word('Is').
sentence_initial_word('It').
sentence_initial_word('Its').
sentence_initial_word('JPN').
sentence_initial_word('John').
sentence_initial_word('Jr').
sentence_initial_word('Jun').
sentence_initial_word('Just').
sentence_initial_word('Kappa').
sentence_initial_word('Key').
sentence_initial_word('Kit').
sentence_initial_word('Koch').
sentence_initial_word('LEW').
sentence_initial_word('LISA').
sentence_initial_word('LON').
sentence_initial_word('LOX').
sentence_initial_word('Lambda').
sentence_initial_word('Large').
sentence_initial_word('Larger').
sentence_initial_word('Larvae').
sentence_initial_word('Lastly').
sentence_initial_word('Late').
sentence_initial_word('Later').
sentence_initial_word('Lead').
sentence_initial_word('Leaf').
sentence_initial_word('Leaves').
sentence_initial_word('Less').
sentence_initial_word('Level').
sentence_initial_word('Lewis').
sentence_initial_word('Light').
sentence_initial_word('Like').
sentence_initial_word('Lisa').
sentence_initial_word('List').
sentence_initial_word('Little').
sentence_initial_word('Liver').
sentence_initial_word('Local').
sentence_initial_word('Long').
sentence_initial_word('Loss').
sentence_initial_word('Low').
sentence_initial_word('Lower').
sentence_initial_word('Lung').
sentence_initial_word('MAIN').
sentence_initial_word('MAN').
sentence_initial_word('MAP').
sentence_initial_word('MHz').
sentence_initial_word('MIXED').
sentence_initial_word('MR').
sentence_initial_word('MRI').
sentence_initial_word('MRS').
sentence_initial_word('MS').
sentence_initial_word('Main').
sentence_initial_word('Major').
sentence_initial_word('Male').
sentence_initial_word('Man').
sentence_initial_word('Many').
sentence_initial_word('Marc').
sentence_initial_word('Mass').
sentence_initial_word('Max').
sentence_initial_word('Me').
sentence_initial_word('Mean').
sentence_initial_word('Med').
sentence_initial_word('Median').
sentence_initial_word('Mel').
sentence_initial_word('Men').
sentence_initial_word('Met').
sentence_initial_word('Meta').
sentence_initial_word('Metal').
sentence_initial_word('Method').
sentence_initial_word('Meyer').
sentence_initial_word('Mg').
sentence_initial_word('Mild').
sentence_initial_word('Mock').
sentence_initial_word('Moles').
sentence_initial_word('Mono').
sentence_initial_word('More').
sentence_initial_word('Most').
sentence_initial_word('Mr').
sentence_initial_word('Much').
sentence_initial_word('NASA').
sentence_initial_word('Nasal').
sentence_initial_word('Natl').
sentence_initial_word('Nearly').
sentence_initial_word('Net').
sentence_initial_word('Never').
sentence_initial_word('New').
sentence_initial_word('Next').
sentence_initial_word('Nine').
sentence_initial_word('Ninety').
sentence_initial_word('No').
sentence_initial_word('Noise').
sentence_initial_word('Non').
sentence_initial_word('None').
sentence_initial_word('Nor').
sentence_initial_word('Normal').
sentence_initial_word('Not').
sentence_initial_word('Note').
sentence_initial_word('Novel').
sentence_initial_word('Now').
sentence_initial_word('Null').
sentence_initial_word('Nurse').
sentence_initial_word('Nurses').
sentence_initial_word('Older').
sentence_initial_word('Omega').
sentence_initial_word('On').
sentence_initial_word('Once').
sentence_initial_word('One').
sentence_initial_word('Only').
sentence_initial_word('Open').
sentence_initial_word('Or').
sentence_initial_word('Oral').
sentence_initial_word('Org').
sentence_initial_word('Orsola').
sentence_initial_word('Os').
sentence_initial_word('Other').
sentence_initial_word('Our').
sentence_initial_word('Out').
sentence_initial_word('Over').
sentence_initial_word('Ow').
sentence_initial_word('Ox').
sentence_initial_word('Oxygen').
sentence_initial_word('PAGE').
sentence_initial_word('PINCH').
sentence_initial_word('Pain').
sentence_initial_word('Par').
sentence_initial_word('Part').
sentence_initial_word('Path').
sentence_initial_word('Paulo').
sentence_initial_word('Peer').
sentence_initial_word('Phase').
sentence_initial_word('Phil').
sentence_initial_word('Phys').
sentence_initial_word('Pit').
sentence_initial_word('Plant').
sentence_initial_word('Plants').
sentence_initial_word('Plasma').
sentence_initial_word('Proper').
sentence_initial_word('Pylori').
sentence_initial_word('REPORT').
sentence_initial_word('Rag').
sentence_initial_word('Ran').
sentence_initial_word('Ransom').
sentence_initial_word('Rapid').
sentence_initial_word('Rates').
sentence_initial_word('Real').
sentence_initial_word('Recent').
sentence_initial_word('Red').
sentence_initial_word('Renal').
sentence_initial_word('Report').
sentence_initial_word('Res').
sentence_initial_word('Result').
sentence_initial_word('Rev').
sentence_initial_word('Review').
sentence_initial_word('Rich').
sentence_initial_word('Risk').
sentence_initial_word('Root').
sentence_initial_word('Roux').
sentence_initial_word('Russet').
sentence_initial_word('Ruth').
sentence_initial_word('SAGES').
sentence_initial_word('SCAR').
sentence_initial_word('SIGN').
sentence_initial_word('SNAP').
sentence_initial_word('SNARE').
sentence_initial_word('SNARF').
sentence_initial_word('SOME').
sentence_initial_word('SOS').
sentence_initial_word('SPORT').
sentence_initial_word('SPOT').
sentence_initial_word('STAT').
sentence_initial_word('STATS').
sentence_initial_word('STOP').
sentence_initial_word('Safety').
sentence_initial_word('Sample').
sentence_initial_word('Scan').
sentence_initial_word('Scout').
sentence_initial_word('Second').
sentence_initial_word('See').
sentence_initial_word('Self').
sentence_initial_word('Semi').
sentence_initial_word('Serum').
sentence_initial_word('Seven').
sentence_initial_word('Severe').
sentence_initial_word('Sex').
sentence_initial_word('Sexual').
sentence_initial_word('She').
sentence_initial_word('Shh').
sentence_initial_word('Shock').
sentence_initial_word('Short').
sentence_initial_word('Side').
sentence_initial_word('Sight').
sentence_initial_word('Sign').
sentence_initial_word('Simple').
sentence_initial_word('Since').
sentence_initial_word('Single').
sentence_initial_word('Sir').
sentence_initial_word('Site').
sentence_initial_word('Six').
sentence_initial_word('Sixty').
sentence_initial_word('Skin').
sentence_initial_word('Slow').
sentence_initial_word('Small').
sentence_initial_word('Smart').
sentence_initial_word('Snow').
sentence_initial_word('So').
sentence_initial_word('Sodium').
sentence_initial_word('Some').
sentence_initial_word('Source').
sentence_initial_word('Spec').
sentence_initial_word('Spleen').
sentence_initial_word('Starch').
sentence_initial_word('Stats').
sentence_initial_word('Steady').
sentence_initial_word('Stem').
sentence_initial_word('Stop').
sentence_initial_word('Stress').
sentence_initial_word('Strong').
sentence_initial_word('Study').
sentence_initial_word('Sub').
sentence_initial_word('Such').
sentence_initial_word('Supp').
sentence_initial_word('Surf').
sentence_initial_word('Swiss').
sentence_initial_word('TANDEM').
sentence_initial_word('THE').
sentence_initial_word('THESE').
sentence_initial_word('THIS').
sentence_initial_word('THREE').
sentence_initial_word('THUS').
sentence_initial_word('TOP').
sentence_initial_word('TRAIL').
sentence_initial_word('TRAP').
sentence_initial_word('Tag').
sentence_initial_word('Taken').
sentence_initial_word('Taking').
sentence_initial_word('Tan').
sentence_initial_word('Tandem').
sentence_initial_word('Tech').
sentence_initial_word('Ten').
sentence_initial_word('Test').
sentence_initial_word('Tests').
sentence_initial_word('That').
sentence_initial_word('The').
sentence_initial_word('Their').
sentence_initial_word('Then').
sentence_initial_word('There').
sentence_initial_word('These').
sentence_initial_word('They').
sentence_initial_word('Thin').
sentence_initial_word('Third').
sentence_initial_word('Thirty').
sentence_initial_word('This').
sentence_initial_word('Thomas').
sentence_initial_word('Those').
sentence_initial_word('Though').
sentence_initial_word('Three').
sentence_initial_word('Thus').
sentence_initial_word('Thy').
sentence_initial_word('Tissue').
sentence_initial_word('Today').
sentence_initial_word('Top').
sentence_initial_word('Torr').
sentence_initial_word('Total').
sentence_initial_word('Toxic').
sentence_initial_word('Train').
sentence_initial_word('Trans').
sentence_initial_word('Trauma').
sentence_initial_word('Trial').
sentence_initial_word('Trials').
sentence_initial_word('True').
sentence_initial_word('Tumor').
sentence_initial_word('Twelve').
sentence_initial_word('Twenty').
sentence_initial_word('Twin').
sentence_initial_word('Two').
sentence_initial_word('Type').
sentence_initial_word('Types').
sentence_initial_word('UK').
sentence_initial_word('US').
sentence_initial_word('USA').
sentence_initial_word('USP').
sentence_initial_word('Ultra').
sentence_initial_word('Under').
sentence_initial_word('Uni').
sentence_initial_word('Unlike').
sentence_initial_word('Up').
sentence_initial_word('Upon').
sentence_initial_word('Uptake').
sentence_initial_word('Use').
sentence_initial_word('Using').
sentence_initial_word('Values').
sentence_initial_word('Venus').
sentence_initial_word('Very').
sentence_initial_word('Viral').
sentence_initial_word('WASP').
sentence_initial_word('WE').
sentence_initial_word('WITH').
sentence_initial_word('Walter').
sentence_initial_word('Water').
sentence_initial_word('We').
sentence_initial_word('Weight').
sentence_initial_word('Well').
sentence_initial_word('Wells').
sentence_initial_word('What').
sentence_initial_word('When').
sentence_initial_word('Which').
sentence_initial_word('While').
sentence_initial_word('Whilst').
sentence_initial_word('White').
sentence_initial_word('Whole').
sentence_initial_word('Why').
sentence_initial_word('Wide').
sentence_initial_word('Wild').
sentence_initial_word('With').
sentence_initial_word('Within').
sentence_initial_word('Women').
sentence_initial_word('Work').
sentence_initial_word('Wound').
sentence_initial_word('Wright').
sentence_initial_word('Wt').
sentence_initial_word('YOU').
sentence_initial_word('Yet').
sentence_initial_word('Young').
sentence_initial_word('Zinc').
