
/****************************************************************************
*
*                          PUBLIC DOMAIN NOTICE                         
*         Lister Hill National Center for Biomedical Communications
*                      National Library of Medicine
*                      National Institues of Health
*           United States Department of Health and Human Services
*                                                                         
*  This software is a United States Government Work under the terms of the
*  United States Copyright Act. It was written as part of the authors'
*  official duties as United States Government employees and contractors
*  and thus cannot be copyrighted. This software is freely available
*  to the public for use. The National Library of Medicine and the
*  United States Government have not placed any restriction on its
*  use or reproduction.
*                                                                        
*  Although all reasonable efforts have been taken to ensure the accuracy 
*  and reliability of the software and data, the National Library of Medicine
*  and the United States Government do not and cannot warrant the performance
*  or results that may be obtained by using this software or data.
*  The National Library of Medicine and the U.S. Government disclaim all
*  warranties, expressed or implied, including warranties of performance,
*  merchantability or fitness for any particular purpose.
*                                                                         
*  For full details, please see the MetaMap Terms & Conditions, available at
*  http://metamap.nlm.nih.gov/MMTnCs.shtml.
*
***************************************************************************/

% File:     sentence_initial_words.pl
% Module:   sentence_initial_words
% Author:   FML
% Purpose:  Define words that are known to begin a sentence
%           immediately after a full stop with no intervening whitespace.

:- module(sentence_initial_words,[
    sentence_initial_word/1
    ]).

% These are all the words in the 2010 Medline Baseline that
% * appear immediately after a "."
% * with no intervening blank space
% * at least 4 times
% * and are no more than 6 characters long.

sentence_initial_word('AIM').
sentence_initial_word('AIMS').
sentence_initial_word('ALL').
sentence_initial_word('AND').
sentence_initial_word('ARE').
sentence_initial_word('ASH').
sentence_initial_word('About').
sentence_initial_word('Acute').
sentence_initial_word('Ad').
sentence_initial_word('Ada').
sentence_initial_word('Ado').
sentence_initial_word('Adult').
sentence_initial_word('After').
sentence_initial_word('Again').
sentence_initial_word('Age').
sentence_initial_word('Aid').
sentence_initial_word('Aim').
sentence_initial_word('Aims').
sentence_initial_word('All').
sentence_initial_word('Also').
sentence_initial_word('Am').
sentence_initial_word('Among').
sentence_initial_word('An').
sentence_initial_word('Anal').
sentence_initial_word('And').
sentence_initial_word('Anti').
sentence_initial_word('Any').
sentence_initial_word('App').
sentence_initial_word('Are').
sentence_initial_word('Art').
sentence_initial_word('As').
sentence_initial_word('Asthma').
sentence_initial_word('BLIP').
sentence_initial_word('BUT').
sentence_initial_word('Based').
sentence_initial_word('Bax').
sentence_initial_word('Before').
sentence_initial_word('Beta').
sentence_initial_word('Bio').
sentence_initial_word('Biol').
sentence_initial_word('Both').
sentence_initial_word('But').
sentence_initial_word('CASE').
sentence_initial_word('CASES').
sentence_initial_word('CAST').
sentence_initial_word('CAT').
sentence_initial_word('CATE').
sentence_initial_word('Can').
sentence_initial_word('Care').
sentence_initial_word('Carr').
sentence_initial_word('Case').
sentence_initial_word('Cat').
sentence_initial_word('Chem').
sentence_initial_word('China').
sentence_initial_word('Clarke').
sentence_initial_word('Common').
sentence_initial_word('Con').
sentence_initial_word('Copper').
sentence_initial_word('Cost').
sentence_initial_word('Cross').
sentence_initial_word('DESIGN').
sentence_initial_word('DNA').
sentence_initial_word('DOSE').
sentence_initial_word('DOT').
sentence_initial_word('Dane').
sentence_initial_word('Data').
sentence_initial_word('Date').
sentence_initial_word('Delta').
sentence_initial_word('Design').
sentence_initial_word('Dimer').
sentence_initial_word('Direct').
sentence_initial_word('Don').
sentence_initial_word('Dose').
sentence_initial_word('Dot').
sentence_initial_word('Double').
sentence_initial_word('Dr').
sentence_initial_word('Drug').
sentence_initial_word('During').
sentence_initial_word('EAT').
sentence_initial_word('EDDA').
sentence_initial_word('ELISA').
sentence_initial_word('ELM').
sentence_initial_word('EST').
sentence_initial_word('Early').
sentence_initial_word('Edin').
sentence_initial_word('Eight').
sentence_initial_word('Eighty').
sentence_initial_word('Eleven').
sentence_initial_word('End').
sentence_initial_word('Energy').
sentence_initial_word('Eng').
sentence_initial_word('Even').
sentence_initial_word('Eye').
sentence_initial_word('FEAT').
sentence_initial_word('FLAG').
sentence_initial_word('Factor').
sentence_initial_word('Fibrin').
sentence_initial_word('Fifty').
sentence_initial_word('Filter').
sentence_initial_word('First').
sentence_initial_word('Five').
sentence_initial_word('Flow').
sentence_initial_word('Follow').
sentence_initial_word('For').
sentence_initial_word('Forty').
sentence_initial_word('Four').
sentence_initial_word('Frank').
sentence_initial_word('Free').
sentence_initial_word('From').
sentence_initial_word('Full').
sentence_initial_word('Future').
sentence_initial_word('GLAND').
sentence_initial_word('GRIN').
sentence_initial_word('Gene').
sentence_initial_word('George').
sentence_initial_word('Given').
sentence_initial_word('Good').
sentence_initial_word('Grade').
sentence_initial_word('Gross').
sentence_initial_word('Group').
sentence_initial_word('HIV').
sentence_initial_word('Hal').
sentence_initial_word('Ham').
sentence_initial_word('He').
sentence_initial_word('Hence').
sentence_initial_word('Hep').
sentence_initial_word('Here').
sentence_initial_word('Herein').
sentence_initial_word('Hex').
sentence_initial_word('High').
sentence_initial_word('Hind').
sentence_initial_word('His').
sentence_initial_word('Hop').
sentence_initial_word('How').
sentence_initial_word('Human').
sentence_initial_word('Hunter').
sentence_initial_word('Indeed').
sentence_initial_word('Info').
sentence_initial_word('Iron').
sentence_initial_word('Is').
sentence_initial_word('It').
sentence_initial_word('Its').
sentence_initial_word('JPN').
sentence_initial_word('John').
sentence_initial_word('Jr').
sentence_initial_word('KEY').
sentence_initial_word('Kappa').
sentence_initial_word('Kb').
sentence_initial_word('Key').
sentence_initial_word('Kg').
sentence_initial_word('Kit').
sentence_initial_word('Km').
sentence_initial_word('Koch').
sentence_initial_word('LISA').
sentence_initial_word('LOX').
sentence_initial_word('Lac').
sentence_initial_word('Large').
sentence_initial_word('Larger').
sentence_initial_word('Lastly').
sentence_initial_word('Late').
sentence_initial_word('Lewis').
sentence_initial_word('Light').
sentence_initial_word('Lisa').
sentence_initial_word('Long').
sentence_initial_word('Low').
sentence_initial_word('MAX').
sentence_initial_word('MED').
sentence_initial_word('MEL').
sentence_initial_word('METHOD').
sentence_initial_word('MG').
sentence_initial_word('MHz').
sentence_initial_word('MIXED').
sentence_initial_word('MRI').
sentence_initial_word('MRS').
sentence_initial_word('Main').
sentence_initial_word('Male').
sentence_initial_word('Many').
sentence_initial_word('Max').
sentence_initial_word('Mb').
sentence_initial_word('Me').
sentence_initial_word('Mean').
sentence_initial_word('Med').
sentence_initial_word('Median').
sentence_initial_word('Method').
sentence_initial_word('Moles').
sentence_initial_word('Mono').
sentence_initial_word('More').
sentence_initial_word('Most').
sentence_initial_word('NASA').
sentence_initial_word('NFL').
sentence_initial_word('Natl').
sentence_initial_word('Net').
sentence_initial_word('Never').
sentence_initial_word('New').
sentence_initial_word('Next').
sentence_initial_word('Nine').
sentence_initial_word('Ninety').
sentence_initial_word('No').
sentence_initial_word('Noise').
sentence_initial_word('Non').
sentence_initial_word('None').
sentence_initial_word('Nor').
sentence_initial_word('Note').
sentence_initial_word('Now').
sentence_initial_word('Null').
sentence_initial_word('Nurses').
sentence_initial_word('OB').
sentence_initial_word('Older').
sentence_initial_word('Omega').
sentence_initial_word('On').
sentence_initial_word('Once').
sentence_initial_word('One').
sentence_initial_word('Only').
sentence_initial_word('Open').
sentence_initial_word('Or').
sentence_initial_word('Oral').
sentence_initial_word('Org').
sentence_initial_word('Orsola').
sentence_initial_word('Other').
sentence_initial_word('Our').
sentence_initial_word('Out').
sentence_initial_word('Over').
sentence_initial_word('PAGE').
sentence_initial_word('PBX').
sentence_initial_word('PEG').
sentence_initial_word('PEP').
sentence_initial_word('PET').
sentence_initial_word('PINCH').
sentence_initial_word('PVC').
sentence_initial_word('Pain').
sentence_initial_word('Par').
sentence_initial_word('Path').
sentence_initial_word('Paulo').
sentence_initial_word('Peer').
sentence_initial_word('Pep').
sentence_initial_word('Phil').
sentence_initial_word('Phys').
sentence_initial_word('Pi').
sentence_initial_word('Pit').
sentence_initial_word('Plasma').
sentence_initial_word('Poly').
sentence_initial_word('Port').
sentence_initial_word('Post').
sentence_initial_word('Pro').
sentence_initial_word('Pub').
sentence_initial_word('Pvt').
sentence_initial_word('Pylori').
sentence_initial_word('QUA').
sentence_initial_word('RCA').
sentence_initial_word('RECENT').
sentence_initial_word('REPORT').
sentence_initial_word('RESULT').
sentence_initial_word('REX').
sentence_initial_word('RNA').
sentence_initial_word('Rag').
sentence_initial_word('Ran').
sentence_initial_word('Rb').
sentence_initial_word('Re').
sentence_initial_word('Real').
sentence_initial_word('Rec').
sentence_initial_word('Recent').
sentence_initial_word('Ref').
sentence_initial_word('Res').
sentence_initial_word('Result').
sentence_initial_word('Rev').
sentence_initial_word('Rho').
sentence_initial_word('Risk').
sentence_initial_word('Roux').
sentence_initial_word('SAGES').
sentence_initial_word('SCAR').
sentence_initial_word('SENS').
sentence_initial_word('SIGN').
sentence_initial_word('SNAP').
sentence_initial_word('SNARE').
sentence_initial_word('SNARF').
sentence_initial_word('SPORT').
sentence_initial_word('STAT').
sentence_initial_word('STOP').
sentence_initial_word('Sal').
sentence_initial_word('Sample').
sentence_initial_word('Scan').
sentence_initial_word('Sci').
sentence_initial_word('Second').
sentence_initial_word('Self').
sentence_initial_word('Semi').
sentence_initial_word('Serum').
sentence_initial_word('Seven').
sentence_initial_word('Sex').
sentence_initial_word('Short').
sentence_initial_word('Sight').
sentence_initial_word('Sign').
sentence_initial_word('Since').
sentence_initial_word('Single').
sentence_initial_word('Site').
sentence_initial_word('Six').
sentence_initial_word('Sixty').
sentence_initial_word('Skin').
sentence_initial_word('Small').
sentence_initial_word('Smart').
sentence_initial_word('Some').
sentence_initial_word('Spec').
sentence_initial_word('Spleen').
sentence_initial_word('Steady').
sentence_initial_word('Stem').
sentence_initial_word('Stop').
sentence_initial_word('Study').
sentence_initial_word('Sub').
sentence_initial_word('Such').
sentence_initial_word('Supp').
sentence_initial_word('Surf').
sentence_initial_word('Swiss').
sentence_initial_word('TANDEM').
sentence_initial_word('TRAIL').
sentence_initial_word('Tag').
sentence_initial_word('Taken').
sentence_initial_word('Tandem').
sentence_initial_word('Tech').
sentence_initial_word('Ten').
sentence_initial_word('Test').
sentence_initial_word('Tet').
sentence_initial_word('That').
sentence_initial_word('The').
sentence_initial_word('Their').
sentence_initial_word('Then').
sentence_initial_word('There').
sentence_initial_word('These').
sentence_initial_word('They').
sentence_initial_word('Third').
sentence_initial_word('Thirty').
sentence_initial_word('This').
sentence_initial_word('Thomas').
sentence_initial_word('Those').
sentence_initial_word('Though').
sentence_initial_word('Three').
sentence_initial_word('Thus').
sentence_initial_word('Thy').
sentence_initial_word('Time').
sentence_initial_word('To').
sentence_initial_word('Today').
sentence_initial_word('Torr').
sentence_initial_word('Total').
sentence_initial_word('Train').
sentence_initial_word('Trans').
sentence_initial_word('Trials').
sentence_initial_word('True').
sentence_initial_word('Tumor').
sentence_initial_word('Twelve').
sentence_initial_word('Twenty').
sentence_initial_word('Two').
sentence_initial_word('Type').
sentence_initial_word('Types').
sentence_initial_word('USA').
sentence_initial_word('USP').
sentence_initial_word('Under').
sentence_initial_word('Uni').
sentence_initial_word('Up').
sentence_initial_word('Use').
sentence_initial_word('Using').
sentence_initial_word('Val').
sentence_initial_word('Venus').
sentence_initial_word('WASP').
sentence_initial_word('WITH').
sentence_initial_word('Water').
sentence_initial_word('We').
sentence_initial_word('Weight').
sentence_initial_word('Well').
sentence_initial_word('What').
sentence_initial_word('When').
sentence_initial_word('While').
sentence_initial_word('Whole').
sentence_initial_word('Why').
sentence_initial_word('With').
sentence_initial_word('Within').
sentence_initial_word('Women').
sentence_initial_word('Work').
sentence_initial_word('Wound').
sentence_initial_word('Wt').
sentence_initial_word('Young').
sentence_initial_word('Zinc').
